name: middleware_dart_opentelemetry
description: Middleware.io's OpenTelemetry SDK for Dart
version: 1.0.6
publisher: middleware.io
repository: https://github.com/middleware-labs/middleware_dart_opentelemetry.git
homepage: https://middleware.io

environment:
  sdk: ^3.0.0

dependencies:
  dartastic_opentelemetry_api: ^1.0.0-beta.7
  fixnum: ^1.1.1
  grpc: ^5.1.0
  http: ^1.5.0
  dio: ^5.9.0
  meta: ^1.16.0
  protobuf: ^6.0.0
  synchronized: ^3.4.0
  web: ^1.1.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  build_runner: ^2.8.0
  dart_flutter_team_lints: ^3.5.2
  mockito: ^5.4.4
  protoc_plugin: ^25.0.0
  pub_semver: ^2.1.0
  pubspec_parse: ^1.5.0
  test: ^1.26.3

# Script commands
scripts:
  test: dart test
  coverage: ./tools/coverage.sh
  coverage_unit_only: dart test --tags=unit --coverage=coverage
